[package]
name = "butter"
version = "0.1.0"
edition = "2021"
default-run = "butter"

[dependencies]
structopt = "0.3.26"
parser = { path = "../parser/" }
hir = { path = "../hir/" }
type-system = { path = "../type-system/" }
